### ISSUE TITLE
Could you explain the hard code threshold

### ISSUE THREAD

**Issue by Flyfoxs** [JoHof/lungmask#17]
Hi JoHof,
I try your mode on COVID data as you mentioned in readme, the performance is really amazing.

And i read you code mask.py, and don't understand the threshold: 600, 1024, 1624. Could you give some explanation. 

Thanks in advance.
  
 tvolslices, xnew_box = utils.preprocess(inimg_raw, resolution=[256, 256])
 tvolslices[tvolslices > 600] = 600
 tvolslices = np.divide((tvolslices + 1024), 1624)

**Comment by JoHof** [comment]
Hi,

great that it works so well! CT intensity is encdoed in Hounsfield Units (HU). In HU the density of air is defined to be -1000.  Ususally the minimum is -1024. 0 is water and bone is 1000 or so. These lines of code basically normalize the values to be between 0 and 1 and cutoff all the values above 600. Because larger than 600 will not contribute beneficial information for lung segmentation. However, this is a bit arbitrary. It would also work with 200 or 1000. But setting a threshold is important because eventually have high density areas (e.g. metal from a pace maker)
