### ISSUE TITLE
the segmentation mask is an all black image

### ISSUE THREAD

**Issue by aakash-saboo** [JoHof/lungmask#7]
Hi
When i give the input path to a dicom file which has whole lung surrounded by tissues, the segmentation mask is an all black image.
can you suggest something about it?

**Comment by JoHof** [comment]
Hi,

is it a single slice?

**Comment by aakash-saboo** [comment]
yes,its a single slice

**Comment by JoHof** [comment]
Does it work if you pass the '--nopostprocess' flag?

**Comment by aakash-saboo** [comment]
Thanks a lot for your quick response.
Yes it works now.
So for single slice i have to pass the flag, but for a folder with several dicoms, I dont need to?

**Comment by JoHof** [comment]
Thanks for pointing this out! For now yes, if you process a full volume (e.g. a series) then let the postprocess on. If you process a single slice deactivate it. However, this is obviously not very intuitive and there should be a single slice postprocess as well. I will change that in the future so that the default parameters work in any way.

However, raw segmentation without postprocessing (fill holes and remove small connected components) are usually quite good and postprocessing doesn't do much.

**Comment by aakash-saboo** [comment]
Thanks a lot for your work,
While processing a folder(containing more than 1 dicom file), when postprocessing is turned off, it gives the right segmentation but when it is turned on(default),it gives only one lung segmentation.

**Comment by JoHof** [comment]
The postprocessing removes connected components from the segmentation that are smaller than 25cm³. So probably the one lung is very small? Is the volume cropped on the z-axis eventually? Anyways, this is a bug and obviously not very well reasoned. The postprocessing should not remove the largest component for any of the two lungs in the future. I will let you now when it's fixed. Unfortunately I am quite busy know. Will do it over the weekend. Back in my head I knew that I have to fix this but I forgot. Thanks again for pointing this out!

**Comment by JoHof** [comment]
To should be fixed in the current version (0.2.3)

**Comment by saranggoel** [comment]
so i am using a .nii file, and its giving me all black images. I have tried using the '--nopostprocess' flag and then not using it, but nothing changed. My .nii file has multiple slices.
